# Generated by Django 3.2.15 on 2022-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('rating', models.CharField(max_length=10)),
                ('reg_id', models.IntegerField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
