# Generated by Django 3.2.15 on 2022-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('user_name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
                ('conform_password', models.CharField(max_length=8)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=25)),
                ('place', models.CharField(max_length=25)),
                ('post', models.CharField(max_length=25)),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'registration',
                'managed': False,
            },
        ),
    ]
