# Generated by Django 3.2.15 on 2022-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('productorder_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('reg_id', models.IntegerField()),
                ('status', models.CharField(max_length=65)),
            ],
            options={
                'db_table': 'product_order',
                'managed': False,
            },
        ),
    ]
