# Generated by Django 3.2.15 on 2022-10-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=25)),
                ('pet_type', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'pet',
                'managed': False,
            },
        ),
    ]
